properties:
    - key: 'server.apppath'
      value : '/yadage-engine/api/v1'
    - key: 'server.url'
      value : 'http://localhost'
    - key: 'server.port'
      value: 25010
    - key: 'app.name'
      value: 'Yadage Workflow Engine @ CDS.NYU'
    - key: 'app.doc'
      value: 'http://localhost:25010/yadage/doc/engine/index.html'
    - key: 'app.debug'
      value: true
    - key: 'app.logdir'
      value: '/home/heiko/projects/adage/engine-api/log'
    - key: 'db.workdir'
      value: '/home/heiko/projects/adage/engine-api/data'
    - key:  'mongo.db'
      value: 'yadage'
